project:
  type: website

website:
  title: "BUA 455"
  navbar:
    left:
      - href: index.qmd
        text: This website provides semester-long access to BUA 455 lecture slides, notes, and R code files, regardless of access to Blackboard.

format:
  html:
    theme: superhero
    css: styles.css
    toc: true

editor: visual
